#!/usr/bin/env bash

work_dir="$(pwd)"
tools_dir="$(cd "$(dirname "$0")" && pwd)"
source "$tools_dir/common.sh"

echo 'Generating autonomic post selector script...' 1>&2
echo "  sources: $TWEET_BASE_DIR/scheduled" 1>&2
echo "  output : $autonomic_post_selector" 1>&2

cat << FIN > "$autonomic_post_selector"
#!/usr/bin/env bash
#
# This file is generated by "generate_autonomic_post_selector.sh".
# Do not modify this file manually.

base_dir="\$(cd "\$(dirname "\$0")" && pwd)"

choose_random_one() {
  local input="\$(cat)"
  local n_lines="\$(echo "\$input" | wc -l)"
  local index=\$(((\$RANDOM % \$n_lines) + 1))
  echo "\$input" | sed -n "\${index}p"
}

extract_response() {
  local source="\$1"
  if [ ! -f "\$source" ]
  then
    echo ""
    return 0
  fi

  local responses="\$(cat "\$source" |
                        grep -v '^#' |
                        grep -v '^\s*\$')"

  [ "\$responses" = '' ] && return 1

  echo "\$responses" | choose_random_one
}

FIN

cd "$TWEET_BASE_DIR"

if [ -d ./scheduled ]
then
  messages_allday="$status_dir/scheduled_allday.txt"
  echo '' > "${messages_allday}.tmp"

  ls ./scheduled/all* |
    sort |
    while read path
  do
    # convert CR+LF => LF for safety.
    nkf -Lu "$path" >> "${messages_allday}.tmp"
    echo '' >> "$messages_allday"
  done
  egrep -v '^#|^\s*$' "${messages_allday}.tmp" > "$messages_allday"
  rm -rf "${messages_allday}.tmp"

  cat << FIN >> "$autonomic_post_selector"
[ "\$DEBUG" != '' ] && echo "Choosing message from \"$messages_allday\"" 1>&2
extract_response "$messages_allday"
exit \$?
FIN
fi

cat << FIN >> "$autonomic_post_selector"

exit 1
FIN

chmod +x "$autonomic_post_selector"
